name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare build environment
      run: |
        rustup target add x86_64-unknown-linux-gnu
        rustup target add i686-unknown-linux-gnu
        curl -L https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-gnu.tar.gz | tar xvz
        mkdir -p releases/linux

    - name: Build x86_64
      run: |
        cargo build --release --target=x86_64-unknown-linux-gnu
        cp target/x86_64-unknown-linux-gnu/release/librespot releases/linux/librespot-linux-x86_64
        chmod +x releases/linux/librespot-linux-x86_64

    - name: Build ARMv8
      run: |
        ./cross build --release --target=aarch64-unknown-linux-gnu
        cp target/aarch64-unknown-linux-gnu/release/librespot releases/linux/librespot-linux-aarch64
        chmod +x releases/linux/librespot-linux-aarch64

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: librespot-linux
        path: releases/

